import os
import re
from pathlib import Path
import json

# ── 白色填充/描边正则（用于生成浅色图标变体） ──
# 匹配 fill="#fff" / stroke="#ffffff" / fill="white" / stroke="white"
WHITE_ATTR_RE = re.compile(
    r'(fill|stroke)="(#[fF]{3,6}|white)"', re.IGNORECASE
)
LIGHT_FILL = "#333333"


def generate_icons_qrc(
        icons_dir="./icons",
        output_qrc="./icons/icons.qrc",
        output_map="app/utils/icon_name_map.py"
):
    extensions = {'.png', '.svg', '.ico', '.jpg', '.jpeg', '.gif'}
    icons_path = Path(icons_dir)

    if not icons_path.exists():
        print(f"⚠️ 图标目录不存在: {icons_path}")
        return

    # 收集图标：key=stem（无后缀名），value=完整文件名
    icon_map = {}
    for file in icons_path.iterdir():
        if file.is_file() and file.suffix.lower() in extensions:
            stem = file.stem
            if stem not in icon_map:
                icon_map[stem] = file.name

    # 生成 .qrc
    qrc_lines = [
        '<!DOCTYPE RCC>',
        '<RCC version="1.0">',
        '<qresource prefix="/icons">'
    ]
    for filename in sorted(icon_map.values()):
        qrc_lines.append(f'    <file>{filename}</file>')
    qrc_lines.extend(['  </qresource>', '</RCC>'])

    # 写入 .qrc
    qrc_path = Path(output_qrc)
    qrc_path.parent.mkdir(parents=True, exist_ok=True)
    with open(qrc_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(qrc_lines))

    # 生成 Python 映射文件：icon_name_map.py
    map_content = "# Auto-generated by generate_icons_qrc.py\n"
    map_content += "ICON_NAME_TO_FILE = "
    map_content += json.dumps(icon_map, indent=4, ensure_ascii=False)

    with open(output_map, 'w', encoding='utf-8') as f:
        f.write(map_content)

    print(f"✅ 生成 {len(icon_map)} 个图标资源")
    print(f"📄 .qrc 文件: {qrc_path}")
    print(f"🗺️  映射文件: {output_map}")


# ── 浅色图标生成 ───────────────────────────────────────

def _should_create_light_variant(svg_path: Path) -> bool:
    """判断是否需要创建浅色变体：含有白色 fill 或 stroke 才需要"""
    content = svg_path.read_text(encoding="utf-8")
    return bool(WHITE_ATTR_RE.search(content))


def _create_light_variant(svg_path: Path, light_dir: Path) -> Path:
    """复制 SVG 并把白色 fill/stroke 替换为深色"""
    content = svg_path.read_text(encoding="utf-8")
    new_content = WHITE_ATTR_RE.sub(r'\1="' + LIGHT_FILL + '"', content)
    out_path = light_dir / svg_path.name
    out_path.write_text(new_content, encoding="utf-8")
    return out_path


def generate_light_icons(
        icons_dir="./icons",
        light_dir="./icons/light",
        output_qrc="./icons/light/icons_light.qrc",
        output_map="app/utils/icon_name_map_light.py",
        output_rc="app/utils/icons_light_rc.py",
):
    """生成浅色模式图标变体 + QRC + 映射 + 编译"""
    extensions = {'.png', '.svg', '.ico', '.jpg', '.jpeg', '.gif'}
    icons_path = Path(icons_dir)
    light_path = Path(light_dir)
    light_path.mkdir(parents=True, exist_ok=True)

    if not icons_path.exists():
        print(f"⚠️ 图标目录不存在: {icons_path}")
        return

    light_map = {}
    created = 0
    skipped = 0

    for file in sorted(icons_path.iterdir()):
        if not file.is_file() or file.suffix.lower() not in extensions:
            continue
        if file.suffix.lower() != '.svg':
            continue  # 只处理 SVG

        if _should_create_light_variant(file):
            _create_light_variant(file, light_path)
            light_map[file.stem] = file.name
            created += 1
            print(f"  ✓ {file.name} → light/{file.name}")
        else:
            skipped += 1
            print(f"  - {file.name} (自有颜色，跳过)")

    print(f"\n✅ 生成 {created} 个浅色图标，跳过 {skipped} 个")

    # 生成 light QRC
    qrc_lines = [
        '<!DOCTYPE RCC>',
        '<RCC version="1.0">',
        '<qresource prefix="/icons_light">'
    ]
    for filename in sorted(light_map.values()):
        qrc_lines.append(f'    <file>{filename}</file>')
    qrc_lines.extend(['  </qresource>', '</RCC>'])

    with open(output_qrc, 'w', encoding='utf-8') as f:
        f.write('\n'.join(qrc_lines))
    print(f"📄 浅色 QRC: {output_qrc}")

    # 生成浅色映射文件
    map_content = "# Auto-generated by generate_icons_qrc.py\n"
    map_content += "ICON_NAME_TO_FILE_LIGHT = "
    map_content += json.dumps(light_map, indent=4, ensure_ascii=False)

    with open(output_map, 'w', encoding='utf-8') as f:
        f.write(map_content)
    print(f"🗺️  浅色映射: {output_map}")

    # 编译 Python 资源文件
    ret = os.system(f"pyrcc5 {output_qrc} -o {output_rc}")
    if ret == 0:
        print(f"✅ 编译成功: {output_rc}")
    else:
        print(f"❌ 编译失败 (exit code {ret}): {output_rc}")


if __name__ == "__main__":
    print("=" * 50)
    print("  生成深色图标资源")
    print("=" * 50)
    generate_icons_qrc()
    os.system("pyrcc5 icons/icons.qrc -o app/utils/icons_rc.py")

    print()
    print("=" * 50)
    print("  生成浅色图标资源")
    print("=" * 50)
    generate_light_icons()
